### PR TITLE
Compile with gcc5.4 (Ubuntu 16.04) needs c++14

### PR DESCRIPTION
**Pull request by Walibu**
Setting compilerflag c++14 for gcc-5.4.0 (Ubuntu16.04), according: https://gcc.gnu.org/projects/cxx-status.html
"Nested namespace definitions" are supported with gcc-6.x

Without this flag I get errors like this:
Cloud/CloudService.h:587:65: error: ‘CloudService::CloudServiceSetting’ is not a class or namespace
                 value = returning->settings.value(CloudService::CloudServiceSetting::DefaultURL, "");

### CODE REVIEW

**Comment by Walibu** [comment]
I was not able to compile GC on Ubuntu 16.04 LTS
I found this solution with the compilerflag setting to c++14 and it works.
Am I alone in having this issue, last time I could compile it was in March 2017
